before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - binary: tms
    env:
      - CGO_ENABLED=0
    main: ./src
    goos:
      - linux
    goarch:
      - amd64

dockers:
  - image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}'
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--platform=linux/amd64"

docker_manifests:
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}'
  - name_template: '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:latest'
    image_templates:
      - '{{ .Env.REGISTRY }}/{{ .Env.IMAGE_NAME }}:{{ .Tag }}'

checksum:
  name_template: 'checksums.txt'
