name: Build & Release

on:
  push:
    branches:
      - "main" # Trigger on pushes to main
    tags:
      - "v*" # Trigger on tags that start with 'v'

permissions: write-all

jobs:
  release:
    name: Build & Release
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin to v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # pin to v3.0.0

      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Run "make docker-build"
        run: make docker-build

<<<<<<< HEAD
      - name: Run "make docker-deploy"
        run: make docker-deploy
=======
  release:
    runs-on: ubuntu-latest

    needs: build

    if: startsWith(github.ref, 'refs/tags/v')

    env:
      REGISTRY: "ghcr.io"
      IMAGE_NAME: "goproslowyo/tms"

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # pin to v4.1.1

      - name: Set up Go
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # pin to v5.0.0
        with:
          go-version: 1.21

      - name: ghcr-login
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # pin to v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push GitHub Release
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8 # pin to v5.0.0
        with:
          version: latest
          args: release --clean
        env:
          REGISTRY: ${{ env.REGISTRY }}
          IMAGE: ${{ env.IMAGE_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> 1741560 (Convert from deprecated flag)
